package fr.iutgon.sae401.serverSide.server.clients;

import java.util.Objects;
import java.util.UUID;

/**
 * @brief Opaque identifier for a connected client.
 * <p>
 * A {@link ClientId} is generated by the server and can be used as a stable key
 * to reference a connection while it is alive.
 */
public record ClientId(String value) {
    public static final ClientId UNKNOWN = new ClientId("unknown");

    public ClientId {
        Objects.requireNonNull(value, "value");
        if (value.isBlank()) {
            throw new IllegalArgumentException("value must not be blank");
        }
    }

    /**
     * @brief Create a random client id.
     */
    public static ClientId random() {
        return new ClientId(UUID.randomUUID().toString());
    }
}
